# Generated by Django 2.0.6 on 2018-06-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nus_code', models.CharField(max_length=200)),
                ('nus_credits', models.FloatField()),
                ('pu_name', models.CharField(max_length=200)),
                ('pu_code', models.CharField(max_length=200)),
                ('pu_title', models.CharField(max_length=200)),
                ('pu_credits', models.FloatField()),
            ],
        ),
    ]
