# Generated by Django 2.0.6 on 2018-06-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20180603_2346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapping',
            unique_together={('nus_code', 'nus_credits', 'pu_name', 'pu_code', 'pu_title', 'pu_credits')},
        ),
    ]
